[package]
name = "block_circulant_codes"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-poly-commit = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
rayon = "1.10"
rand = "0.8"
sha2 = "0.10"
thiserror = "2.0.19"
blake3 = "=1.8.3"
zstd = "0.13"
whir = { git = "https://github.com/worldfnd/whir.git", rev = "92652ca01e215548c98e11834e110c43994b94c1" }

[dev-dependencies]
merlin = "1.3.0"
